### PR TITLE
Feature/roadmap py pi 020 update

### PR DESCRIPTION
**Pull request by Pietervanhalem**
Fixed some minor errors in testing and made the tests ready for halem PyPI update (to version 0.2.0)

### CODE REVIEW

**Comment by uijl** [comment]
Should the notebooks be in the test folder? The same hold for all the .csv files in the static folder.

**Comment by uijl** [comment]
And if this PR is accepted, can we remove branch "feature/roadmap"?

**Comment by Pietervanhalem** [comment]
Yes if the PR is accepted these branches can be deleted. I created a new branch since my source tree bugged-out.

I don't see any .csv file in the folder OpenCLS/static.  All the files in the I have deleted some of the files from the folder OpenCLSim/tests/Roadmap, the files that are still there create the roadmap needed for testing. I think it is use full to keep these file for later updates.

**Comment by uijl** [comment]
Changes have been merged with another branch and will be continued with that PR.

**Pull request closed without merging**
