### PR TITLE
Fix docker geos version

### PR DESCRIPTION
**Pull request by SiggyF**
libgeos is installed. IT installed a specific version. This is no longer available after upgrade of base image. 
this change will install latest version of libgeos. This should match with the python version.

### CODE REVIEW

**Review by Pietervanhalem — COMMENTED** [review]
Why do the tests fail?

**Comment by GerbenJdeBoer** [comment]
Does test fail because of https://github.com/Azure/static-web-apps/issues/941

**Comment by SiggyF** [comment]
This branch solves a problem with geos, but at the same time azure decided that we are over our limit of available branches. 
We currently only have 3 active branches. So my first approach is to increase the number of allowed branches. 
After that I'll try to follow [this approach](https://stackoverflow.com/questions/74069643/how-to-delete-azure-static-web-app-branch-preview-environments-when-deleting-sou). The issue there is that you have to program  yourself how to cleanup old branches. The implementation is in javascript / npm, so I would first need to adapt that or add npm (too much tech for 1 repo).

**Comment by SiggyF** [comment]
According to an open issue at Azure this is a [hard limit](https://github.com/Azure/static-web-apps/issues/765). They are working on it, though. I'll manual delete them and consider to script the deletion, but that's also a bit error prone. 

I can also switch to netlify, which supports more branches. But then we have yet another subscription (already have azure, sonarcloud, circleci).

**Comment by SiggyF** [comment]
I have disabled building the book on PR for now. Then we should not run into the issue. For now, we have to test changes to the book locally.

**Comment by GerbenJdeBoer** [comment]
ok

**Review by GerbenJdeBoer — APPROVED** [review]

**Pull request merged**
